server:
  port: 9092

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  #循环依赖问题，允许循环引用,否则项目启动失败  SpringBoot2.6.0之后默认禁止的
  main:
    allow-circular-references: true